@startuml
|Користувач|
start
: Натискає на кнопку "Вхід в систему";

|Система Boar|
: Перенаправляє на сторінку входу в систему;

|Користувач|
: Вводить:
 - поштову скриньку/ім'я користувача
 - пароль;

|Система Boar|
: Перевіряє введені дані;
note right #ffaaaa
<b> Можливо
<b> EX_U3.01
<b> EX_U3.02
end note

: Перевіряє значення user.status;
note right #ffaaaa
<b> Можливо
<b> EX_U3.03
end note

|Користувач|
- Отримує доступ до свого облікового запису;
stop;
@enduml
