@startuml

|Користувач|
start
: Відкриває листа від системи Boar;
note left #ffaaaa
<b> Можливо
<b> EX_U2.01
<b> EX_U2.02
end note

: Натискає на кнопку "Підтвердити";


|Система Boar|
: Вносить відповідні записи в базу даних;
note right #ffaaaa
<b> Можливо
<b> EX_U2.03
end note

:Змінює user.status на значення "Зареєстровано";

: Перенаправляє на початкову сторінку системи;

|Користувач|
: Отримує доступ до облікового запису;
stop;
@enduml
