@startuml

|Керівник групи|
start
: Натискає на кнопку "Видалити завдання";

|Система boar|
: Встановлює завдання яке потрібно видалити;
: Видаляє завдання;

|Керівник групи|
stop;
@enduml
