@startuml
|Менеджер проєкту|
start
: Переглядає технічне завдання;


: Натискає на кнопку "Редагувати технічне завдання";

|Система Boar|
: Перенаправляє на сторінку редагування технічного завдання;

|Менеджер проєкту|
: Може змінити:
 - назву
 - текст технічного завдання
 - крайній термін виконання;

|Система Boar|
: Оброблює;
note right #ffaaaa
<b> Можливо
<b> EX_U9.01
end note

: Оновлює дані;
note right #ffaaaa
<b> Можливо
<b> EX_U9.02
end note

|Менеджер проєкту|
stop;
@enduml
