@startuml
|Керівник групи|
start
: Натискає на кнопку "Створити завдання";

|Система boar|
: Перенаправляє на сторінку створення завдання;

|Керівник групи|
: Вводить:
 - назву завдання
 - текст завдання
 - учасника, який повинен виконати завдання
 - крайній термін виконання;

|Система boar|
: Оброблює введені дані;
note right #ffaaaa
<b> Можливо
<b> EX_1
<b> EX_2
end note
: Встановлює дату та час створення та автора завдання;
: Створює нове завдання;
: Додає створене завдання на сторінку проєкту;
: Сповіщає учасника проєкту про появу нового завдання;

: Вносить в базу даних;
note right #ffaaaa
<b> Можливо
<b> EX_3
end note


|Керівник групи|
stop;
@enduml
