@startuml
|Менеджер проєкту|
start
: Натискає на кнопку "Створити технічне завдання";

|Система Boar|
: Перенаправляє на сторінку створення технічного завдання;

|Менеджер проєкту|
: Вводить:
 - назву
 - текст технічного завдання
 - крайній термін виконання;

|Система Boar|
: Оброблює;
note right #ffaaaa
<b> Можливо
<b> EX_U8.01
end note

: Встановлює:
 - автора
 - дату та час створення;

: Вносить в базу даних;
note right #ffaaaa
<b> Можливо
<b> EX_U8.02
end note

|Менеджер проєкту|
stop;
@enduml
