@startuml
|Користувач|
start
: Натискає на кнопку "Створити новий проєкт";

|Система Boar|
: Перенаправляє на сторінку створення проєкту;

|Користувач|
: Вказує:
 - назву проєкту
 - опис проєкту
 - учасників проєкту та їх ролі;

|Система Boar|
: Оброблює введені дані;
note right #ffaaaa
<b> Можливо
<b> EX_U3.01
end note

: Встановлює роль користувача, що створив
проєкт як "Проєктний менеджер";

: Вносить в базу даних;

|Користувач|
stop;
@enduml