@startuml
|Користувач|
start
:Натискає на кнопку "Переглянути прогресс";
|Система|
:Перенаправляє на сторінку прогрессу;
:Обробляє кількості завданнь з різними статусами;
note right #ffaaaa
<b> Можливо
<b> EX_U09.1
end note
:Створює відношення завдань зі статусом "Виконано" до всіх інших;
|Користувач|
:Отримує прогресс у вигляді відношення;
stop
@enduml
