@startuml
actor :Замовник: as man5

Rectangle :Команда: as  team {
  actor :Розробник: as man1
  actor :Тестувальник: as man2
  actor :Керівник_групи: as man3
  actor :Менеджер_проєкту: as man4
  
  man1 -r----> (man2): Рев'ю(**BC.005.002**)
  
  man2 -l----> (man1): Повернути завдання\n до розробника(**BC.004.001**)
  man2 -u--> (man3): Відправити завдання\n до керівника групи(**BC.004.002**)
  
  man3 -d----> (man1): Повернути завдання\n розробнику через неякісне\n виконання(**BC.003.003**)
  man3 -d----> (man1): Видати завдання\n розробнику(**BC.003.001**)
  man3 -r---> (man4): Відправити виконане\n завдання до менеджера\n проєкту(**BC.003.002**)
  
  man4 -l---> (man3): Передати завдання\n керівнику групи(**BC.002.002**)
  
  man4 -r-|> (man5): Продемонструвати\n роботу замовнику(**BC.002.001**)
  man5 -l-|> (man4): Скласти/оновити\n технічне завдання(**BC.001.001**)
}
@enduml