-- MySQL Script generated by MySQL Workbench
-- Sun Nov 29 16:29:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Project` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `ProjectId` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ProjectId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Metadata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Metadata` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Metadata` (
  `key` VARCHAR(45) NOT NULL,
  `value` VARCHAR(2000) NULL,
  `type` VARCHAR(45) NOT NULL,
  `ProjectId` INT NOT NULL,
  INDEX `fk_Metadata_Project_idx` (`ProjectId` ASC) VISIBLE,
  CONSTRAINT `fk_Metadata_Project`
    FOREIGN KEY (`ProjectId`)
    REFERENCES `mydb`.`Project` (`ProjectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UserStatus` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UserStatus` (
  `UserStatusId` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserStatusId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(500) NULL,
  `UserStatusId` INT NOT NULL,
  PRIMARY KEY (`UserId`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_User_UserStatus1_idx` (`UserStatusId` ASC) VISIBLE,
  CONSTRAINT `fk_User_UserStatus1`
    FOREIGN KEY (`UserStatusId`)
    REFERENCES `mydb`.`UserStatus` (`UserStatusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Specification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Specification` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Specification` (
  `name` VARCHAR(1000) NOT NULL,
  `text` LONGTEXT NOT NULL,
  `datetime` DATETIME(10) NOT NULL,
  `deadline` DATE NOT NULL,
  `ProjectId` INT NOT NULL,
  `SpecificationId` INT NOT NULL AUTO_INCREMENT,
  `Author` INT NOT NULL,
  INDEX `fk_Specification_Project1_idx` (`ProjectId` ASC) VISIBLE,
  PRIMARY KEY (`SpecificationId`),
  INDEX `fk_Specification_User1_idx` (`Author` ASC) VISIBLE,
  CONSTRAINT `fk_Specification_Project1`
    FOREIGN KEY (`ProjectId`)
    REFERENCES `mydb`.`Project` (`ProjectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specification_User1`
    FOREIGN KEY (`Author`)
    REFERENCES `mydb`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TaskStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TaskStatus` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TaskStatus` (
  `TaskStatusId` INT NOT NULL,
  `status` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`TaskStatusId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Task` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Task` (
  `name` VARCHAR(1000) NOT NULL,
  `text` LONGTEXT NOT NULL,
  `datetime` DATETIME(10) NOT NULL,
  `deadline` DATE NOT NULL,
  `TaskStatusId` INT NOT NULL,
  `SpecificationId` INT NOT NULL,
  `TaskId` INT NOT NULL AUTO_INCREMENT,
  `Author` INT NOT NULL,
  `AssignedTo` INT NOT NULL,
  INDEX `fk_Task_TaskStatus1_idx` (`TaskStatusId` ASC) VISIBLE,
  INDEX `fk_Task_Specification1_idx` (`SpecificationId` ASC) VISIBLE,
  PRIMARY KEY (`TaskId`),
  INDEX `fk_Task_User1_idx` (`Author` ASC) VISIBLE,
  INDEX `fk_Task_User2_idx` (`AssignedTo` ASC) VISIBLE,
  CONSTRAINT `fk_Task_TaskStatus1`
    FOREIGN KEY (`TaskStatusId`)
    REFERENCES `mydb`.`TaskStatus` (`TaskStatusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_Specification1`
    FOREIGN KEY (`SpecificationId`)
    REFERENCES `mydb`.`Specification` (`SpecificationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_User1`
    FOREIGN KEY (`Author`)
    REFERENCES `mydb`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_User2`
    FOREIGN KEY (`AssignedTo`)
    REFERENCES `mydb`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Artifact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Artifact` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Artifact` (
  `ArtifactId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(2000) NOT NULL,
  `link` VARCHAR(500) NOT NULL,
  `status` TINYINT(1) NULL,
  PRIMARY KEY (`ArtifactId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ArtifactConnector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ArtifactConnector` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ArtifactConnector` (
  `TaskId` INT NOT NULL,
  `ArtifactId` INT NOT NULL,
  PRIMARY KEY (`TaskId`, `ArtifactId`),
  INDEX `fk_Task_has_Artifact_Artifact1_idx` (`ArtifactId` ASC) VISIBLE,
  INDEX `fk_Task_has_Artifact_Task1_idx` (`TaskId` ASC) VISIBLE,
  CONSTRAINT `fk_Task_has_Artifact_Task1`
    FOREIGN KEY (`TaskId`)
    REFERENCES `mydb`.`Task` (`TaskId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_has_Artifact_Artifact1`
    FOREIGN KEY (`ArtifactId`)
    REFERENCES `mydb`.`Artifact` (`ArtifactId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `RoleId` INT NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RoleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Access`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Access` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Access` (
  `ProjectId` INT NOT NULL,
  `UserId` INT NOT NULL,
  `Role_RoleId` INT NOT NULL,
  PRIMARY KEY (`ProjectId`, `UserId`),
  INDEX `fk_Project_has_User_User1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_Project_has_User_Project1_idx` (`ProjectId` ASC) VISIBLE,
  INDEX `fk_Access_Role1_idx` (`Role_RoleId` ASC) VISIBLE,
  CONSTRAINT `fk_Project_has_User_Project1`
    FOREIGN KEY (`ProjectId`)
    REFERENCES `mydb`.`Project` (`ProjectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_has_User_User1`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Access_Role1`
    FOREIGN KEY (`Role_RoleId`)
    REFERENCES `mydb`.`Role` (`RoleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
